spring.application.name=erp
spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true
security.whitelist=/api/auth/login,/api/auth/register,/api/public/**,/swagger-ui/**,/v3/api-docs/**

jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}

