spring.application.name=erp
spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.properties.hibernate.integrator_provider=com.dat.erp.utils.EncryptionIntegrator
spring.jpa.properties.hibernate.session_factory.interceptor=com.dat.erp.interceptor.EncryptionInterceptor

